# Create separate batch files for WXS, WGS, RNA-Seq
# These are written to . directory
# Batch files have 3 columns: UUID, SampleName, and gdc-client output filename
# SampleName is generated by combining case, experimental strategy, and tumor/normal.  These are meant for human readability
# comments starting with # are ignored in batch files

source gdc-import.config

OUT="$CONFIG_HOME/WXS.batch.dat"
awk 'BEGIN{FS="\t";OFS="\t"}{if ($3 == "WXS") print}' $SR | sort | bash $IMPORTGDC_HOME/batch.import/batch_from_SR.sh - > $OUT
echo Written to $OUT

OUT="$CONFIG_HOME/WGS.batch.dat"
awk 'BEGIN{FS="\t";OFS="\t"}{if ($3 == "WGS") print}' $SR | sort | bash $IMPORTGDC_HOME/batch.import/batch_from_SR.sh - > $OUT
echo Written to $OUT

OUT="$CONFIG_HOME/RNA-Seq.batch.dat"
awk 'BEGIN{FS="\t";OFS="\t"}{if ($3 == "RNA-Seq") print}' $SR | sort | bash $IMPORTGDC_HOME/batch.import/batch_from_SR.sh - > $OUT
echo Written to $OUT
